In [3]:
import numpy as np
import numpy.linalg as la

In [55]:
A = np.array([[-3,8],[2,3]])
print(A)

[[-3  8]
 [ 2  3]]


In [56]:
l = -5
print(l)

-5


In [69]:
x = np.array([[0],[2]])

test = A @ x
test2 = l * x

print(test)
print(test2)

if (test[0] == test2[0]) and (test[1] == test2[1]):
    print('This is an eigenvector, check 1')
else:
    if (test2[0] % test[0] == 0) and (test2[1] % test[1] == 0):
        print('This is an eigenvector, check 2')
    else:
         print('This is not an eigenvector')
    

[[16]
 [ 6]]
[[  0]
 [-10]]
This is not an eigenvector


In [63]:
#test[0] % test2[0]

35%6

5